"""
Step 06: TSX Metadata Extractor
Extracts field IDs, labels, handlers, and screen structure from React TSX files.
Outputs tsx_metadata.json for use by Step 07.

Features:
- Extracts fields WITH existing id attributes
- Extracts fields WITHOUT id attributes and generates deterministic IDs
- Marks generated IDs with id_generated=True flag for Step 08 to inject

Usage:
    python step_06_tsx_extractor.py <input_tsx_file> <output_json_file>
    
Example:
    python step_06_tsx_extractor.py ui_react_component.tsx tsx_metadata.json
"""

import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple
from dataclasses import dataclass, asdict
from enum import Enum


class ElementType(Enum):
    INPUT = "input"
    SELECT = "select"
    BUTTON = "button"
    CHECKBOX = "checkbox"
    TEXTAREA = "textarea"


@dataclass
class ExtractedField:
    tsx_id: str
    element_type: str
    input_type: Optional[str]
    label: Optional[str]
    placeholder: Optional[str]
    default_value: Optional[str]
    screen_name: str
    section_title: Optional[str]
    line_number: int
    id_generated: bool = False  # True if ID was generated by extractor (not in original TSX)
    original_input_line: Optional[str] = None  # Store original line for Step 08 to find and replace
    
    def to_dict(self) -> Dict[str, Any]:
        result = {}
        for k, v in asdict(self).items():
            if v is not None and v != False:
                result[k] = v
            elif k == 'id_generated' and v == True:
                result[k] = v
        return result


@dataclass
class ExtractedHandler:
    function_name: str
    trigger_element: str
    button_text: Optional[str]
    screen_name: str
    line_number: int
    is_stub: bool  # True if just calls showNotification
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ExtractedStateVariable:
    name: str
    has_mock_data: bool
    mock_data_line_start: Optional[int]
    mock_data_line_end: Optional[int]
    initial_value_type: str  # 'empty_array', 'empty_object', 'mock_data', 'primitive'
    
    def to_dict(self) -> Dict[str, Any]:
        return {k: v for k, v in asdict(self).items() if v is not None}


@dataclass
class ExtractedScreen:
    component_name: str
    line_start: int
    line_end: int
    fields: List[ExtractedField]
    handlers: List[ExtractedHandler]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'component_name': self.component_name,
            'line_start': self.line_start,
            'line_end': self.line_end,
            'fields': [f.to_dict() for f in self.fields],
            'handlers': [h.to_dict() for h in self.handlers]
        }


class TSXExtractor:
    """
    Extracts metadata from React TSX files using regex-based parsing.
    Designed for deterministic, reproducible extraction.
    """
    
    def __init__(self, tsx_content: str):
        self.content = tsx_content
        self.lines = tsx_content.splitlines()
        self._generated_ids = set()  # Track generated IDs to avoid duplicates
        
    def extract_all(self) -> Dict[str, Any]:
        """Main extraction method. Returns complete metadata."""
        screens = self._extract_screens()
        state_variables = self._extract_state_variables()
        top_level_handlers = self._extract_top_level_handlers()
        
        # Count fields with generated IDs
        generated_id_count = sum(
            1 for screen in screens 
            for field in screen.fields 
            if field.id_generated
        )
        
        return {
            'extraction_metadata': {
                'total_lines': len(self.lines),
                'screens_found': len(screens),
                'state_variables_found': len(state_variables),
                'top_level_handlers_found': len(top_level_handlers),
                'fields_with_generated_ids': generated_id_count
            },
            'screens': [s.to_dict() for s in screens],
            'state_variables': [sv.to_dict() for sv in state_variables],
            'top_level_handlers': [h.to_dict() for h in top_level_handlers],
            'mock_data_locations': self._find_mock_data_locations(state_variables)
        }
    
    def _extract_screens(self) -> List[ExtractedScreen]:
        """Extract all screen components (functions returning JSX)."""
        screens = []
        
        # Pattern: const ScreenName = () => ( or function ScreenName()
        screen_pattern = re.compile(
            r'const\s+(\w+Screen)\s*=\s*\(\s*\)\s*=>\s*\(?',
            re.MULTILINE
        )
        
        for match in screen_pattern.finditer(self.content):
            screen_name = match.group(1)
            start_pos = match.start()
            start_line = self.content[:start_pos].count('\n') + 1
            
            # Find the end of this screen component
            end_line = self._find_component_end(start_line)
            
            # Extract screen content
            screen_content = '\n'.join(self.lines[start_line - 1:end_line])
            
            # Extract fields and handlers within this screen
            fields = self._extract_fields_from_content(screen_content, screen_name, start_line)
            handlers = self._extract_handlers_from_content(screen_content, screen_name, start_line)
            
            screens.append(ExtractedScreen(
                component_name=screen_name,
                line_start=start_line,
                line_end=end_line,
                fields=fields,
                handlers=handlers
            ))
        
        return screens
    
    def _find_component_end(self, start_line: int) -> int:
        """Find where a component ends by tracking parentheses/braces."""
        paren_count = 0
        brace_count = 0
        started = False
        
        for i in range(start_line - 1, len(self.lines)):
            line = self.lines[i]
            
            for char in line:
                if char == '(':
                    paren_count += 1
                    started = True
                elif char == ')':
                    paren_count -= 1
                elif char == '{':
                    brace_count += 1
                elif char == '}':
                    brace_count -= 1
            
            # Component ends when we return to zero after starting
            if started and paren_count == 0 and brace_count == 0:
                return i + 1
        
        return len(self.lines)
    
    def _extract_fields_from_content(
        self, 
        content: str, 
        screen_name: str,
        base_line: int
    ) -> List[ExtractedField]:
        """Extract all input fields from screen content, including those without id."""
        fields = []
        processed_positions = set()  # Track positions to avoid duplicates
        
        # Pattern for input elements WITH id
        input_with_id_pattern = re.compile(
            r'<input\s+([^>]*?)id\s*=\s*["\']([^"\']+)["\']([^>]*?)/?>',
            re.DOTALL | re.IGNORECASE
        )
        
        # Pattern for input elements WITHOUT id
        input_without_id_pattern = re.compile(
            r'<input\s+(?![^>]*\bid\s*=)([^>]*?)/?>',
            re.DOTALL | re.IGNORECASE
        )
        
        # Pattern for select elements WITH id
        select_with_id_pattern = re.compile(
            r'<select\s+([^>]*?)id\s*=\s*["\']([^"\']+)["\']([^>]*?)>',
            re.DOTALL | re.IGNORECASE
        )
        
        # Pattern for select elements WITHOUT id
        select_without_id_pattern = re.compile(
            r'<select\s+(?![^>]*\bid\s*=)([^>]*?)>',
            re.DOTALL | re.IGNORECASE
        )
        
        # Pattern for textarea elements WITH id
        textarea_with_id_pattern = re.compile(
            r'<textarea\s+([^>]*?)id\s*=\s*["\']([^"\']+)["\']([^>]*?)>',
            re.DOTALL | re.IGNORECASE
        )
        
        # Pattern for textarea elements WITHOUT id
        textarea_without_id_pattern = re.compile(
            r'<textarea\s+(?![^>]*\bid\s*=)([^>]*?)>',
            re.DOTALL | re.IGNORECASE
        )
        
        # ============================================
        # 1. Extract inputs WITH id (existing logic)
        # ============================================
        for match in input_with_id_pattern.finditer(content):
            before_id = match.group(1)
            field_id = match.group(2)
            after_id = match.group(3)
            full_attrs = before_id + after_id
            
            input_type = self._extract_attribute(full_attrs, 'type') or 'text'
            placeholder = self._extract_attribute(full_attrs, 'placeholder')
            default_value = self._extract_attribute(full_attrs, 'defaultValue')
            
            label = self._find_label_for_element(content, match.start(), field_id)
            section_title = self._find_section_title(content, match.start())
            line_number = base_line + content[:match.start()].count('\n')
            
            processed_positions.add(match.start())
            
            fields.append(ExtractedField(
                tsx_id=field_id,
                element_type='input',
                input_type=input_type,
                label=label,
                placeholder=placeholder,
                default_value=default_value,
                screen_name=screen_name,
                section_title=section_title,
                line_number=line_number,
                id_generated=False
            ))
        
        # ============================================
        # 2. Extract inputs WITHOUT id (NEW)
        # ============================================
        for match in input_without_id_pattern.finditer(content):
            # Skip if already processed (position overlap check)
            if self._is_position_processed(match.start(), processed_positions, tolerance=10):
                continue
            
            full_attrs = match.group(1)
            
            input_type = self._extract_attribute(full_attrs, 'type') or 'text'
            
            # Skip hidden inputs and submit buttons
            if input_type in ('hidden', 'submit', 'button'):
                continue
            
            placeholder = self._extract_attribute(full_attrs, 'placeholder')
            default_value = self._extract_attribute(full_attrs, 'defaultValue')
            
            # Find label to generate ID
            label = self._find_label_for_element(content, match.start(), None)
            section_title = self._find_section_title(content, match.start())
            line_number = base_line + content[:match.start()].count('\n')
            
            # Generate deterministic ID
            generated_id = self._generate_field_id(screen_name, label, placeholder, line_number)
            
            if generated_id:
                # Store original input line for Step 08 to find and replace
                original_line = self._get_original_input_line(content, match.start(), match.end())
                
                processed_positions.add(match.start())
                
                fields.append(ExtractedField(
                    tsx_id=generated_id,
                    element_type='input',
                    input_type=input_type,
                    label=label,
                    placeholder=placeholder,
                    default_value=default_value,
                    screen_name=screen_name,
                    section_title=section_title,
                    line_number=line_number,
                    id_generated=True,
                    original_input_line=original_line
                ))
        
        # ============================================
        # 3. Extract selects WITH id
        # ============================================
        for match in select_with_id_pattern.finditer(content):
            before_id = match.group(1)
            field_id = match.group(2)
            after_id = match.group(3)
            
            label = self._find_label_for_element(content, match.start(), field_id)
            section_title = self._find_section_title(content, match.start())
            line_number = base_line + content[:match.start()].count('\n')
            
            processed_positions.add(match.start())
            
            fields.append(ExtractedField(
                tsx_id=field_id,
                element_type='select',
                input_type='select',
                label=label,
                placeholder=None,
                default_value=None,
                screen_name=screen_name,
                section_title=section_title,
                line_number=line_number,
                id_generated=False
            ))
        
        # ============================================
        # 4. Extract selects WITHOUT id (NEW)
        # ============================================
        for match in select_without_id_pattern.finditer(content):
            if self._is_position_processed(match.start(), processed_positions, tolerance=10):
                continue
            
            label = self._find_label_for_element(content, match.start(), None)
            section_title = self._find_section_title(content, match.start())
            line_number = base_line + content[:match.start()].count('\n')
            
            generated_id = self._generate_field_id(screen_name, label, None, line_number)
            
            if generated_id:
                original_line = self._get_original_input_line(content, match.start(), match.end())
                processed_positions.add(match.start())
                
                fields.append(ExtractedField(
                    tsx_id=generated_id,
                    element_type='select',
                    input_type='select',
                    label=label,
                    placeholder=None,
                    default_value=None,
                    screen_name=screen_name,
                    section_title=section_title,
                    line_number=line_number,
                    id_generated=True,
                    original_input_line=original_line
                ))
        
        # ============================================
        # 5. Extract textareas WITH id
        # ============================================
        for match in textarea_with_id_pattern.finditer(content):
            before_id = match.group(1)
            field_id = match.group(2)
            after_id = match.group(3)
            full_attrs = before_id + after_id
            
            placeholder = self._extract_attribute(full_attrs, 'placeholder')
            label = self._find_label_for_element(content, match.start(), field_id)
            section_title = self._find_section_title(content, match.start())
            line_number = base_line + content[:match.start()].count('\n')
            
            processed_positions.add(match.start())
            
            fields.append(ExtractedField(
                tsx_id=field_id,
                element_type='textarea',
                input_type='textarea',
                label=label,
                placeholder=placeholder,
                default_value=None,
                screen_name=screen_name,
                section_title=section_title,
                line_number=line_number,
                id_generated=False
            ))
        
        # ============================================
        # 6. Extract textareas WITHOUT id (NEW)
        # ============================================
        for match in textarea_without_id_pattern.finditer(content):
            if self._is_position_processed(match.start(), processed_positions, tolerance=10):
                continue
            
            full_attrs = match.group(1)
            placeholder = self._extract_attribute(full_attrs, 'placeholder')
            label = self._find_label_for_element(content, match.start(), None)
            section_title = self._find_section_title(content, match.start())
            line_number = base_line + content[:match.start()].count('\n')
            
            generated_id = self._generate_field_id(screen_name, label, placeholder, line_number)
            
            if generated_id:
                original_line = self._get_original_input_line(content, match.start(), match.end())
                processed_positions.add(match.start())
                
                fields.append(ExtractedField(
                    tsx_id=generated_id,
                    element_type='textarea',
                    input_type='textarea',
                    label=label,
                    placeholder=placeholder,
                    default_value=None,
                    screen_name=screen_name,
                    section_title=section_title,
                    line_number=line_number,
                    id_generated=True,
                    original_input_line=original_line
                ))
        
        # Sort by line number for deterministic order
        fields.sort(key=lambda f: f.line_number)
        
        return fields
    
    def _is_position_processed(self, pos: int, processed: set, tolerance: int = 10) -> bool:
        """Check if a position (or nearby position) was already processed."""
        for p in processed:
            if abs(p - pos) <= tolerance:
                return True
        return False
    
    def _get_original_input_line(self, content: str, start: int, end: int) -> str:
        """Extract the original input/select/textarea tag for later replacement."""
        # Extend to capture full tag if it spans multiple lines
        tag_content = content[start:end]
        
        # If tag doesn't end properly, extend to find closing
        if not tag_content.rstrip().endswith('>'):
            extended_end = content.find('>', end)
            if extended_end != -1:
                tag_content = content[start:extended_end + 1]
        
        return tag_content.strip()
    
    def _generate_field_id(
        self, 
        screen_name: str, 
        label: Optional[str], 
        placeholder: Optional[str],
        line_number: int
    ) -> Optional[str]:
        """Generate a deterministic field ID from label or placeholder."""
        
        base_id = None
        
        # Priority 1: Use label
        if label:
            base_id = self._normalize_to_camel_case(label)
        
        # Priority 2: Use placeholder (strip common prefixes)
        elif placeholder:
            cleaned = re.sub(
                r'^(Enter|Select|Choose|Input|Type|Search|Filter)\s+', 
                '', 
                placeholder, 
                flags=re.IGNORECASE
            )
            cleaned = re.sub(r'\s*\.\.\.+$', '', cleaned)  # Remove trailing ...
            base_id = self._normalize_to_camel_case(cleaned)
        
        # Priority 3: Fallback to screen + line number
        if not base_id:
            screen_prefix = self._normalize_to_camel_case(screen_name.replace('Screen', ''))
            base_id = f"{screen_prefix}Field{line_number}"
        
        # Ensure uniqueness
        final_id = base_id
        counter = 1
        while final_id in self._generated_ids:
            final_id = f"{base_id}{counter}"
            counter += 1
        
        self._generated_ids.add(final_id)
        return final_id
    
    def _normalize_to_camel_case(self, text: str) -> str:
        """Convert text to camelCase."""
        if not text:
            return ''
        
        # Remove special characters, split on spaces/underscores/hyphens
        words = re.split(r'[^a-zA-Z0-9]+', text)
        words = [w for w in words if w]
        
        if not words:
            return ''
        
        # First word lowercase, rest capitalized
        result = words[0].lower()
        for word in words[1:]:
            if word:
                result += word.capitalize()
        
        return result
    
    def _extract_handlers_from_content(
        self, 
        content: str, 
        screen_name: str,
        base_line: int
    ) -> List[ExtractedHandler]:
        """Extract button click handlers from screen content."""
        handlers = []
        
        # Pattern for onClick handlers on buttons
        button_pattern = re.compile(
            r'<button\s+[^>]*onClick\s*=\s*\{([^}]+)\}[^>]*>([^<]*)</button>',
            re.DOTALL | re.IGNORECASE
        )
        
        for match in button_pattern.finditer(content):
            handler_expr = match.group(1).strip()
            button_text = match.group(2).strip()
            
            # Clean button text
            button_text = self._clean_button_text(button_text)
            
            # Extract function name from handler expression
            func_name = self._extract_function_name(handler_expr)
            
            if func_name:
                line_number = base_line + content[:match.start()].count('\n')
                
                # Determine if this is a stub (just shows notification)
                is_stub = 'showNotification' in handler_expr and func_name == 'showNotification'
                
                handlers.append(ExtractedHandler(
                    function_name=func_name,
                    trigger_element='button',
                    button_text=button_text if button_text else None,
                    screen_name=screen_name,
                    line_number=line_number,
                    is_stub=is_stub
                ))
        
        return handlers
    
    def _extract_top_level_handlers(self) -> List[ExtractedHandler]:
        """Extract handler functions defined at the top level (not in screens)."""
        handlers = []
        
        # Pattern for const funcName = ...
        func_pattern = re.compile(
            r'const\s+(\w+)\s*=\s*(?:\([^)]*\)|)\s*(?::\s*[^=]+)?\s*=>\s*\{',
            re.MULTILINE
        )
        
        for match in func_pattern.finditer(self.content):
            func_name = match.group(1)
            line_number = self.content[:match.start()].count('\n') + 1
            
            # Skip screen components
            if 'Screen' in func_name:
                continue
            
            # Find function body to check if it's a stub
            body_start = match.end()
            func_body = self._extract_function_body(body_start)
            is_stub = self._is_stub_function(func_body)
            
            handlers.append(ExtractedHandler(
                function_name=func_name,
                trigger_element='function',
                button_text=None,
                screen_name='top_level',
                line_number=line_number,
                is_stub=is_stub
            ))
        
        return handlers
    
    def _extract_state_variables(self) -> List[ExtractedStateVariable]:
        """Extract useState declarations."""
        state_vars = []
        
        # Pattern for useState
        state_pattern = re.compile(
            r'const\s+\[(\w+),\s*\w+\]\s*=\s*useState[^(]*\(([^;]+)',
            re.MULTILINE | re.DOTALL
        )
        
        for match in state_pattern.finditer(self.content):
            var_name = match.group(1)
            initial_value = match.group(2).strip()
            
            # Calculate line numbers
            line_start = self.content[:match.start()].count('\n') + 1
            line_end = self.content[:match.end()].count('\n') + 1
            
            # Determine if this has mock data
            has_mock_data = False
            value_type = 'primitive'
            
            if initial_value.startswith('['):
                if initial_value == '[]':
                    value_type = 'empty_array'
                else:
                    value_type = 'mock_data'
                    has_mock_data = True
            elif initial_value.startswith('{'):
                if initial_value == '{}':
                    value_type = 'empty_object'
                elif len(initial_value) > 50:  # Likely mock data
                    value_type = 'mock_data'
                    has_mock_data = True
            
            state_vars.append(ExtractedStateVariable(
                name=var_name,
                has_mock_data=has_mock_data,
                mock_data_line_start=line_start if has_mock_data else None,
                mock_data_line_end=line_end if has_mock_data else None,
                initial_value_type=value_type
            ))
        
        return state_vars
    
    def _find_mock_data_locations(
        self, 
        state_vars: List[ExtractedStateVariable]
    ) -> List[Dict[str, Any]]:
        """Identify all mock data that needs to be removed."""
        locations = []
        
        for sv in state_vars:
            if sv.has_mock_data:
                locations.append({
                    'variable_name': sv.name,
                    'line_start': sv.mock_data_line_start,
                    'line_end': sv.mock_data_line_end,
                    'action': 'replace_with_empty_array' if 'array' in sv.initial_value_type or sv.initial_value_type == 'mock_data' else 'replace_with_empty_object'
                })
        
        return locations
    
    def _extract_attribute(self, attrs_str: str, attr_name: str) -> Optional[str]:
        """Extract attribute value from attributes string."""
        # Pattern for attribute="value" or attribute='value' or attribute={value}
        patterns = [
            rf'{attr_name}\s*=\s*"([^"]*)"',
            rf"{attr_name}\s*=\s*'([^']*)'",
            rf'{attr_name}\s*=\s*\{{["\']([^"\']*)["\']?\}}',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, attrs_str, re.IGNORECASE)
            if match:
                return match.group(1)
        
        return None
    
    def _find_label_for_element(
        self, 
        content: str, 
        element_pos: int, 
        element_id: Optional[str]
    ) -> Optional[str]:
        """Find the label associated with an input element."""
        
        # Strategy 1: Look for label with htmlFor matching id (if id provided)
        if element_id:
            htmlfor_pattern = re.compile(
                rf'<label\s+[^>]*htmlFor\s*=\s*["\']{element_id}["\'][^>]*>([^<]+)</label>',
                re.IGNORECASE
            )
            match = htmlfor_pattern.search(content)
            if match:
                return match.group(1).strip()
        
        # Strategy 2: Look for label immediately before element (within same div)
        search_start = max(0, element_pos - 500)
        search_content = content[search_start:element_pos]
        
        # Find last label before the element
        label_pattern = re.compile(
            r'<label[^>]*>([^<]+)</label>\s*$',
            re.IGNORECASE | re.MULTILINE
        )
        
        matches = list(label_pattern.finditer(search_content))
        if matches:
            # Get the last (closest) label
            return matches[-1].group(1).strip()
        
        # Strategy 3: Look for label in same container div
        label_in_div_pattern = re.compile(
            r'<label[^>]*>([^<]+)</label>',
            re.IGNORECASE
        )
        
        # Find the containing div
        div_start = search_content.rfind('<div')
        if div_start != -1:
            div_content = search_content[div_start:]
            match = label_in_div_pattern.search(div_content)
            if match:
                return match.group(1).strip()
        
        return None
    
    def _find_section_title(self, content: str, element_pos: int) -> Optional[str]:
        """Find the section/heading title for an element."""
        search_start = max(0, element_pos - 1000)
        search_content = content[search_start:element_pos]
        
        # Look for h3, h4 or elements with title-like patterns
        patterns = [
            r'<h3[^>]*>([^<]+)</h3>',
            r'<h4[^>]*>([^<]+)</h4>',
            r'title\s*=\s*["\']([^"\']+)["\']',
            r'"title":\s*"([^"]+)"',
        ]
        
        for pattern in patterns:
            matches = list(re.finditer(pattern, search_content, re.IGNORECASE))
            if matches:
                return matches[-1].group(1).strip()
        
        return None
    
    def _extract_function_name(self, handler_expr: str) -> Optional[str]:
        """Extract function name from onClick expression."""
        # Direct function reference: onClick={addToWorklist}
        if re.match(r'^\w+$', handler_expr):
            return handler_expr
        
        # Arrow function calling another function: onClick={() => addToWorklist()}
        match = re.search(r'\(\)\s*=>\s*(\w+)\s*\(', handler_expr)
        if match:
            return match.group(1)
        
        # Arrow function with showNotification (stub)
        if 'showNotification' in handler_expr:
            return 'showNotification'
        
        # Arrow function with showModal
        if 'showModal' in handler_expr:
            return 'showModal'
        
        # Arrow function with setState pattern
        match = re.search(r'\(\)\s*=>\s*(set\w+)\s*\(', handler_expr)
        if match:
            return match.group(1)
        
        return None
    
    def _extract_function_body(self, start_pos: int) -> str:
        """Extract function body starting from opening brace."""
        brace_count = 1
        pos = start_pos
        
        while pos < len(self.content) and brace_count > 0:
            char = self.content[pos]
            if char == '{':
                brace_count += 1
            elif char == '}':
                brace_count -= 1
            pos += 1
        
        return self.content[start_pos:pos]
    
    def _is_stub_function(self, func_content: str) -> bool:
        """Check if function is just a stub (only shows notification)."""
        # Remove whitespace and check content
        cleaned = re.sub(r'\s+', ' ', func_content).strip()
        
        # Stub patterns
        stub_patterns = [
            r"showNotification\s*\([^)]+\)\s*;?\s*\}$",
            r"console\.log\s*\([^)]+\)\s*;?\s*\}$",
        ]
        
        for pattern in stub_patterns:
            if re.search(pattern, cleaned):
                return True
        
        return False
    
    def _clean_button_text(self, text: str) -> str:
        """Clean button text by removing emoji and extra whitespace."""
        # Remove emoji using Unicode ranges (encoding-safe)
        text = re.sub(r'[\U0001F300-\U0001F9FF\u2600-\u26FF\u2700-\u27BF]+', '', text)
        # Remove unicode escape sequences
        text = re.sub(r'\\u[0-9a-fA-F]{4}', '', text)
        return text.strip()


def main():
    """Main entry point."""
    if len(sys.argv) < 3:
        print("Usage: python step_06_tsx_extractor.py <input_tsx_file> <output_json_file> [application_config.json]")
        print("Example: python step_06_tsx_extractor.py ui_react_component.tsx tsx_metadata.json application_config.json")
        print("\nOptional: Provide application_config.json to analyze acceptance criteria coverage")
        sys.exit(1)
    
    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2])
    config_file = Path(sys.argv[3]) if len(sys.argv) > 3 else None
    
    if not input_file.exists():
        print(f"[ERROR] Input file not found: {input_file}")
        sys.exit(1)
    
    print(f"--- Step 06: TSX Metadata Extraction ---")
    print(f"Input: {input_file}")
    print(f"Output: {output_file}")
    if config_file:
        print(f"Config: {config_file}")
    
    # Read TSX content
    tsx_content = input_file.read_text(encoding='utf-8')
    
    # Extract metadata
    extractor = TSXExtractor(tsx_content)
    metadata = extractor.extract_all()
    
    # Add source file info
    metadata['source_file'] = str(input_file)
    
    # If config file provided, add acceptance criteria coverage analysis
    if config_file and config_file.exists():
        ac_coverage = _analyze_ac_coverage(metadata, config_file)
        metadata['ac_coverage'] = ac_coverage
        print(f"[INFO] Acceptance criteria coverage analysis added")
    
    # Write output
    output_file.write_text(json.dumps(metadata, indent=2), encoding='utf-8')
    
    # Print summary
    print(f"\n[SUCCESS] Extraction complete:")
    print(f"  - Screens found: {metadata['extraction_metadata']['screens_found']}")
    print(f"  - State variables: {metadata['extraction_metadata']['state_variables_found']}")
    print(f"  - Top-level handlers: {metadata['extraction_metadata']['top_level_handlers_found']}")
    print(f"  - Fields with generated IDs: {metadata['extraction_metadata']['fields_with_generated_ids']}")
    print(f"  - Mock data locations: {len(metadata['mock_data_locations'])}")
    
    for screen in metadata['screens']:
        print(f"\n  Screen: {screen['component_name']}")
        print(f"    - Fields: {len(screen['fields'])}")
        print(f"    - Handlers: {len(screen['handlers'])}")
        
        for field in screen['fields']:
            id_marker = " [GENERATED]" if field.get('id_generated') else ""
            print(f"      * {field['tsx_id']}: label='{field.get('label', 'N/A')}'{id_marker}")
    
    # Print AC coverage summary if available
    if 'ac_coverage' in metadata:
        print(f"\n  --- Acceptance Criteria Coverage ---")
        for story_id, story_coverage in metadata['ac_coverage'].items():
            print(f"\n  {story_id}:")
            for ac_id, ac_data in story_coverage.items():
                coverage_pct = ac_data.get('coverage_percent', 0)
                status = "✓" if coverage_pct == 100 else "✗"
                print(f"    {status} {ac_id}: {ac_data.get('title', '')} - {coverage_pct}%")
                if ac_data.get('missing_fields'):
                    print(f"      Missing: {', '.join(ac_data['missing_fields'][:5])}")


def _analyze_ac_coverage(metadata: Dict[str, Any], config_file: Path) -> Dict[str, Any]:
    """Analyze acceptance criteria coverage based on extracted TSX fields."""
    
    with open(config_file, 'r', encoding='utf-8') as f:
        config = json.load(f)
    
    acceptance_criteria = config.get('acceptance_criteria', [])
    screen_layouts = config.get('screen_layouts', [])
    
    # Build map of story_id -> screen_name -> required fields
    story_fields = {}
    for layout in screen_layouts:
        story_id = layout.get('story_id', '')
        fields = []
        for section in layout.get('layout_sections', []):
            for field in section.get('fields', []):
                fields.append({
                    'id': field.get('id', ''),
                    'label': field.get('label', ''),
                    'type': field.get('type', ''),
                    'required': field.get('required', False)
                })
        story_fields[story_id] = {
            'screen_name': layout.get('screen_name', ''),
            'fields': fields
        }
    
    # Build map of extracted TSX fields by label (lowercase for matching)
    tsx_fields_by_label = {}
    tsx_fields_by_id = {}
    for screen in metadata.get('screens', []):
        for field in screen.get('fields', []):
            label = (field.get('label') or '').lower().strip()
            tsx_id = (field.get('tsx_id') or '').lower()
            if label:
                tsx_fields_by_label[label] = field
            if tsx_id:
                tsx_fields_by_id[tsx_id] = field
    
    # Group acceptance criteria by story
    ac_by_story = {}
    for ac in acceptance_criteria:
        story_id = ac.get('source_story_id', '')
        if story_id not in ac_by_story:
            ac_by_story[story_id] = []
        ac_by_story[story_id].append(ac)
    
    # Analyze coverage for each story
    coverage_result = {}
    
    for story_id, acs in ac_by_story.items():
        story_coverage = {}
        story_field_info = story_fields.get(story_id, {})
        required_fields = story_field_info.get('fields', [])
        
        for ac in acs:
            ac_id = ac.get('id', '')
            ac_title = ac.get('title', '')
            
            # Find fields mentioned in this AC's "then" clause
            then_text = ' '.join(ac.get('then', []))
            
            # Check which required fields are covered in TSX
            found_fields = []
            missing_fields = []
            
            for field in required_fields:
                field_label = field.get('label', '').lower().strip()
                field_id = field.get('id', '').lower()
                
                # Check if field exists in TSX (by label or id)
                found = (field_label in tsx_fields_by_label or 
                        field_id in tsx_fields_by_id or
                        any(field_label in k for k in tsx_fields_by_label.keys()))
                
                if found:
                    found_fields.append(field.get('label', field.get('id', '')))
                else:
                    missing_fields.append(field.get('label', field.get('id', '')))
            
            # Calculate coverage
            total_fields = len(required_fields)
            coverage_pct = round((len(found_fields) / total_fields * 100) if total_fields > 0 else 100)
            
            story_coverage[ac_id] = {
                'title': ac_title,
                'total_required_fields': total_fields,
                'found_in_tsx': len(found_fields),
                'missing_count': len(missing_fields),
                'coverage_percent': coverage_pct,
                'found_fields': found_fields,
                'missing_fields': missing_fields
            }
        
        if story_coverage:
            coverage_result[story_id] = story_coverage
    
    return coverage_result


if __name__ == '__main__':
    main()
